### ISSUE TITLE
Debug enabled?

### ISSUE THREAD

**Issue by KGHague** [delabrcd/rockband-drums-usb#2]
I've attempted to read the debug stream on RX/TX with a TTL adapter but am getting no data.  It appears that SERIAL_DEBUG is not defined by default in your compiled binary?  I'm also unable to compile with it defined.

adapter_common.cpp: In function ‘void debug(const char*)’:
adapter_common.cpp:35:18: error: request for member ‘print’ in ‘1’, which is of non-class type ‘int’
     SERIAL_DEBUG.print(msg);
                  ^
adapter_common.cpp: In function ‘void SetupHardware()’:
adapter_common.cpp:328:18: error: request for member ‘begin’ in ‘1’, which is of non-class type ‘int’
     SERIAL_DEBUG.begin(DEBUG_USART_BAUDRATE);

**Comment by delabrcd** [comment]
You'll need to enable it by defining the Arduino HardwareSerial device to use. In this case, Serial1. [Uncomment this line](https://github.com/delabrcd/openrb-instruments/blob/9e8648a05cf2ae91177dfc99b3b968905e3b3460/Config/AdapterConfig.h#L19)
